/* ═══════════════════════════════════════════════════════════════════
   en.js — traduction anglaise du site.
   Indexée par sélecteur CSS : aucun balisage à ajouter dans index.html.
   Le français n'est jamais modifié ; ce fichier ne sert qu'à l'affichage.

   RÈGLES
   • Titre du spectacle : « La Rage de Vivre » reste en français (décision RN).
   • Titres d'œuvres : original publié (Really the Blues, Beneath the Underdog,
     To Be or Not to Bop, Rewind and Play, The Bacchae, The Seagull…).
   • Noms propres, théâtres, compagnies, titres de morceaux : inchangés.
   • CITATIONS DE MEZZ : Really the Blues est écrit EN ANGLAIS ; celles du
     dossier sont des traductions françaises et l'original n'a pas pu être
     récupéré (archive.org en prêt restreint). Décision RN : on LAISSE LE
     FRANÇAIS, signalé dans l'attribution.
   • Glissant : traduction propre, signalée « trans. from the French ».
   • On ne touche jamais aux noms porteurs de data-bio ni au lien image de
     Mezz : seuls les libellés de rôle sont remplacés.
   ═══════════════════════════════════════════════════════════════════ */
window.I18N_EN = {

  title: "La Rage de Vivre — dossier",
  description: "La Rage de Vivre — a solo music-theatre piece by Raphaël Naasz, around Mezz Mezzrow and jazz. Interactive presentation dossier.",
  pdf: { href: "assets/dossier-en.pdf", download: "La Rage de Vivre - dossier EN.pdf" },

  map: {

    /* ══════ Écran d'entrée & interface ══════ */
    "#intro-btn": "Enter &amp; listen",
    "#intro .intro-sous": "This dossier is meant to be heard.<br>Turn on your device’s sound,<br>then enter.",
    "#intro .intro-pdf": "↓ Download the dossier (PDF)",
    "#intro .intro-pied": "scroll to explore",
    "#seq-skip": "Skip intro ›",
    ".fleche-indic .txt": "click here",
    ".indication-clic": "click here",
    "#panneau-g .tap-hint": "tap to freeze",

    /* ══════ Couverture (on ne touche PAS aux noms : ils portent data-bio) ══════ */
    ".byline span:nth-of-type(1)": "From the memoir by",
    ".byline span:nth-of-type(3)": "and Bernard Wolfe",
    ".noms .credits-role": ["writer, performer, musician", "director", "assistant director"],
    ".creation": "Creation 2027-2028",

    /* ══════ Page 5 — citations laissées en français, attribution adaptée ══════ */
    ".citation .qui": [
      "Mezz Mezzrow — Really the Blues, p. 423 · French translation",
      "Mezz Mezzrow — Really the Blues, p. 424 · French translation"
    ],

    /* ══════ Double page — grand extrait (français), attribution adaptée ══════ */
    ".hi-credit": "— Milton Mezzrow &amp; Bernard Wolfe, <em>Really the Blues</em>, 1946, pp. 422–424 · quoted here in the French translation (<em>La Rage de Vivre</em>)",

    /* ══════ Switches A/B (fabriqués par le JS du site) ══════ */
    "#ab-p9 .ab-legende": "Same chord changes, two eras",
    "#ab-p10 .ab-legende": "Two ways out of bebop, and Mezzrow.",
    ".ab-toggle": { "aria-label": "Choose a version" },

    /* ══════ Panneaux — « Pourquoi ce livre » ══════ */
    "#src-p2": {
      "data-titre": "Why this book",
      html: "<p>My history with jazz is, first of all, a history of absences.</p>" +
        "<p>My older brother was a saxophonist. He was fifteen years older than me, and like any much younger brother, I loved what he loved, I took everything from him, I copied him, forever trying to resemble him in every way; he was my idol.<br>When I was thirteen he left to settle in Canada — not a violent break, more a polite disappearance of the bond, a silent divorce. The jazz he played and loved stayed behind, on this side of the Atlantic, in the space he had left. I began by studying classical music — the bassoon first — then I started listening to jazz the way you listen to someone who is no longer there. To make his absence exist as something other than a void.</p>"
    },

    "#src-p3": "<p>That particular relationship to jazz — a music loved because there is a lack behind it, inhabited rather than possessed, reached only by returning to it again and again — is perhaps the first thing I share with Mezzrow. Not the music itself. The structure.</p>" +
      "<p>I discovered La Rage de vivre at the CNSAD, in my third year, on the advice of Xavier Gallais, Margaux Eskenazi and Florient Azoulay. I had been given the parade scene to play — without yet any of the questions this work would end up raising. A few weeks earlier, Camille — a classmate — had died of cardiac arrest in front of me, in the street. I tried to revive her with a defibrillator that didn’t work. It didn’t work.</p>" +
      "<p>Ten years later I wrote a text about that moment. I built it by taking up the incidental form of John Coltrane’s solos — those cries I could hear deep inside me and forced myself to swallow so as to stay lucid and try to save her. And even in that gesture — borrowing Coltrane’s form to say what I could not shout — I was using a cultural language that was not my own.</p>",

    "#src-p4": "<p>And that is what comes back now as a question I cannot dodge: even what is most intimate in my relationship to jazz is already a succession of borrowings, of absences inhabited by forms taken from elsewhere.</p>" +
      "<p>By what right?</p>" +
      "<p>I cannot fully answer that question: I am white, I am not Jewish, I am not American. I have no obvious legitimacy in carrying this story. Mezz Mezzrow had none either — no racial legitimacy, little musical legitimacy, no narrative legitimacy. He was not the greatest, not the most righteous, not the most entitled to be there. And yet there he was — whole, burning, defenceless, convinced that he was. And that may also be the condition of the actor, of the performer-musician I have become.</p>" +
      "<p>This book imposed itself on me at a time when I was meeting death for the first time. I am not returning to it in order to adapt it. I am returning to it in order to answer it — a dialogue, ten years on, made of agreements, disagreements, reconciliations and contradictions held together, with nothing ever closing.</p>",

    /* ══════ Panneaux — « Une vie » ══════ */
    "#src-p6": {
      "data-titre": "A LIFE",
      html: "<p>Milton Mesirow, known as “Mezz Mezzrow”, was born in 1899 on the West Side of Chicago, into a lower-middle-class Jewish family of Russian origin. He was sent to the reformatory at Pontiac, Illinois. It was there that he discovered the blues and learned music — first by hearing it sung by the Black inmates, then by playing it with them, on saxophone, in the prison’s mixed band. It was in playing that he felt, for the first time, that he was one of them.</p>" +
        "<p>It was there too that he witnessed a race riot, between Black inmates and Southerners, from which he emerged shaken. The connection took hold: a café owner in Missouri had thrown him out, Jew that he was, taking him for a Black man, and the rabbi of his childhood taught that Moses and Solomon were Black. Jews and Black people, he concluded, are on the same side. He left Pontiac with his mind made up: he would be a musician, a “Black musician”, and would reveal the blues as only Black people know how.</p>" +
        "<p>The music he discovered had no reigning soloist yet. The New Orleans style is a collective polyphony, almost anonymous, in which cornet, clarinet and trombone wind together into a single march — a joy wrested from segregation and three hundred years of slavery, carried in the body as a shared, collective necessity.</p>" +
        "<p>Born in New Orleans at the turn of the century, in a crossroads city where French, Spanish, Creole, African and Anglo-American people meet, it comes out of the mixing of their musics: European military brass bands, Caribbean dance rhythms, African-American work songs, hymns and ragtime. It is a street music, played at parades, funerals and celebrations, which takes the name New Orleans before travelling up to Chicago — where Mezz, precisely, will encounter it.</p>"
    },

    "#src-p7": "<p>In the Chicago of the 1920s, Mezz becomes a figure on the scene. He crosses paths with King Oliver, Armstrong, Bechet, Jimmy Noone, Baby Dodds, the young Bix Beiderbecke.</p>" +
      "<p>Admiration turns to devotion: he tells of driving for hours to Indiana, a revolutionary Armstrong record under his arm, to play it for his friend Bix.</p>" +
      "<p>And it is precisely in those years that jazz shifts its centre of gravity. On that record Armstrong invents the solo — Mezz recounts the legend of it, up to the spontaneous invention of scat. A single voice detaches itself from the polyphony; the improvised chorus becomes the heart of the music. The Chicago style Mezz learns (Bix, <em>Singin’ the Blues</em>) is already a white derivation of that Black invention. He is aware of it, and he writes it.</p>" +
      "<p>He is a clarinettist, a saxophonist, and technically not good enough. Boris Vian, in a 1948 column, notes that he “tends to let his clarinet play all by itself” and relies on “clichés that quickly pall” (<em>Chroniques de jazz</em>, La Jeune Parque, 1967, p. 119). He moves among the greatest and he is not as good as they are. He knows it. He hears it every night. And yet nothing dents his faith: he believes himself the bearer of what cannot be learned — the spirit of the origins, the joy of the real blues.</p>",

    "#src-p8": "<p>Jazz, having already left New Orleans for Chicago, is now fleeing towards New York. Mezz follows: contracts grow scarce, and just before the crash of 1929 he arrives in Harlem.</p>" +
      "<p>There he finds unemployment and poverty, and fights against it. He doubts he is still an artist: to get by, he starts selling Mexican marijuana and becomes the most famous weed dealer in the city. He speaks jive, immerses himself entirely in Black culture and never stops, in the book, offering us the proof of it — he says he enters the community through service, hustle, language and shared daily life.</p>" +
      "<p>The 1930s are also the years when jazz becomes an industry. Swing — big bands, records, hits — is written, arranged music, made to get crowds dancing: the height of jazz as entertainment.</p>" +
      "<p>This is the age of Tin Pan Alley, that New York “street of pots and pans” where hits are turned out on an assembly line, almost in Taylorist fashion. It is exactly what Mezz despises: the commercial dilution of a music born elsewhere, out of necessity.</p>" +
      "<p>Against that industrialisation, Mezz turns back to the origins. He becomes one of the architects of the New Orleans revival — the movement which, against swing, brings the jazz of the early days back up to the surface. In 1938, for the French critic Hugues Panassié, he organises and finances sessions bringing together Tommy Ladnier and Sidney Bechet. He later starts his own label, King Jazz Records, where he plays alongside Bechet. For a time he acts as Louis Armstrong’s manager. He dreams of a mixed band with him, manages it for a few weeks, then has to stop, caught up by opium and heroin, and goes through a forced withdrawal.</p>",

    "#src-p9": "<p>In 1940 he is arrested at the door of a club with some sixty joints on him. In prison he demands to be treated as a Black man and obtains his transfer to the Black section — and it is from there that the central scene of the book will come, the parade.</p>" +
      "<p>He has married Johnnie Mae, a Black woman; he lives in Harlem; he declared himself a “voluntary negro” on his draft card. He is not playing at being Black: he is convinced he has “crossed the line” for good.</p>" +
      "<p>And at the very moment he is sinking into the past of jazz, a few streets away, without him, jazz is already inventing its future. In the jam sessions at Minton’s Playhouse, <span class='lien-switch'>Dizzy Gillespie, Charlie Parker and Thelonious Monk are working out bebop</span>: punishing tempos, inverted changes, harmony saturated to the point where an intruder can no longer follow. A virtuosity conceived as a wall — tritone substitutions, II-V-I multiplied, unpredictable key changes. The aim is explicit: to discourage those who come and sit in and take jazz over without paying its price. You no longer make people dance, you make a claim. Complexity becomes a weapon, a border, a way of stating the cost, the origin, the precise address of the music, a struggle against appropriation by white producers. Is jazz still a dance music?</p>" +
      "<p><em>Really the Blues</em> appears in 1946, co-written with Bernard Wolfe — a Jewish intellectual, a Yale graduate, once Trotsky’s secretary in Mexico. The French translation, <em>La Rage de vivre</em>, appears in 1950 from Corrêa, with a preface by Henry Miller. The book lands on the exact hinge: Mezz writes the monument to the jazz of the origins at the very moment that music is already outstripped, when bebop has overturned everything. And the book mistrusts itself: in an appendix Wolfe writes an essay, “Ecstatic in Blackface”, arguing that the “authentic” Black entertainer, fetishised for the purity and spontaneity of his expression, is in part a projection of the white fan. What Mezz believes he loves in Blackness is, in part, an image manufactured by the white gaze — and Mezz is as much its producer as its consumer.</p>",

    "#src-p10": "<p>From here, two tempos part ways. Mezz’s stops: after the war he freezes into the guardian of a “pure” jazz, that of New Orleans and Chicago, and fights the bebop he judges decadent. He takes part in the first Nice Jazz Festival in 1948 and settles in France; Paris becomes his permanent home for his last twenty years. He puts together bands with French musicians such as Claude Luter, and records in Paris. The other tempo, the music’s, carries on without him: modal jazz opens up the changes and trades the harmonic race for broad sustained fields (Miles, <em>Kind of Blue</em>); hard bop hardens bebop with a return to blues and gospel (Mingus) — and, through collective improvisation, comes back round to the polyphony of New Orleans, but codified to the extreme. And this advance is not only formal: it is political.</p>" +
      "<p>In the America of the 1950s and 1960s — the marches, the bus boycotts, civil rights — the music becomes a claim: Black pride, anger, the assertion of a belonging no one else has the right to sign (Mingus, Max Roach, the Coltrane of <em>Alabama</em>, Coleman). In 1957, Baldwin was writing <em>Sonny’s Blues</em>.</p>",

    "#src-p11": "<p>Then free jazz.</p>" +
      "<p>Ornette Coleman opens the breach — a jazz with no fixed changes, no imposed chord, where the melody goes where it likes; Coltrane commits to it in turn, soon Albert Ayler, Archie Shepp. They break with tonality, with tempo, with the chorus structure, and reconnect with the blues of the origins but freed from every rule. With Coltrane the saxophone becomes a trance: torn phrases jostling and piling over one another at an unheard-of speed, sheets of notes — what critics will call <em>sheets of sound</em> — a vertiginous drop into the low register followed at once by a hallucinatory climb into the highest. A rage, a dark and tragic violence, inseparable from the America of those years. Shepp makes it an explicit weapon; Coltrane pushes the quest as far as mysticism. It is no longer a school, it is an escape offered to everyone: once again jazz leaves behind everything it could be assigned to.</p>",

    "#src-p12": "<p>In the span of a single life, jazz went from the street band to abstraction, to political struggle. Mezz dies in Paris in 1972, faithful to the end to the music he loved, buried at Père-Lachaise, the guardian of a music jazz had left behind thirty years earlier. It is the story of a man who wanted to <em>become</em> what he loved — and what his own gaze, in its turn, was manufacturing.</p>",

    "#src-p15": {
      "data-titre": "PASSING",
      html: "<p>In early twentieth-century America, to be Jewish is not yet to be fully white. There is a structural solidarity — not identical, not equivalent — between Mezz’s marginality and that of the Black musicians he moves among.</p>" +
        "<p>But over the decades American Jews assimilate, and whiten socially. Mezz loses his strangeness at the very moment his love of Black culture grows more radical. And it is here that he becomes a singular figure, against the current of a whole generation.</p>" +
        "<p>Blackface is an American theatrical practice in which white performers blackened their faces to play Black characters — caricatural, servile, debased. Many of these performers were Jewish: Al Jolson, Eddie Cantor. The historian Michael Rogin analysed this continuum in <em>Blackface, White Noise</em> (1996): for Jews who had emigrated from Eastern Europe, still perceived as a doubtful racial otherness, blackface functioned as a rite of passage into whiteness. You borrow the Black man’s mask in order to become, by contrast, white. Jolson embodies this perfectly: the son of Lithuanian Jewish immigrants, he becomes a national star by blackening his face — and in doing so becomes American, white, assimilated. The Black mask is the ladder you climb.</p>" +
        "<p>Mezz makes exactly the opposite move. Jazz is not for him a costume to look more American, a mask you wear in order to rise. It is the place where he refuses to become what America wants to make of him. Where Jolson blackens himself in order to whiten, Mezz sinks into Black culture in order to descend — as far as declaring himself <em>Negro</em> on his prison papers, as far as marriage, as far as Harlem. He takes the very gesture of all Jewish blackface and inverts it term for term: no longer a passage towards the norm, but a desertion of the norm. That is what makes him at once moving and troubling — for this gesture of descent remains a gesture he chose, unlike the Black musicians around him.</p>"
    },

    /* ══════ Panneaux — note d'intention ══════ */
    "#src-int-1": {
      "data-titre": "INTENTIONS",
      html: "<p>Ten years ago, <em>La Rage de Vivre</em> imposed itself on me. The autobiography of a Jewish clarinettist and saxophonist from Chicago who spent twenty years trying to become Black by sheer will. A man who never lets go. At the book’s climax, during a musical parade in the prison on Hart’s Island, he lets something go: he improvises, and believes he is finally playing the blues. He believes he grasps its message: life is good, it is good to be alive, in spite of his shortcomings, the difficulty of being in the world, the harshness of life.</p>" +
        "<p>For me that message is not so much the blues’ as, quite simply, his own, Milton Mezzrow’s. In improvising, Mezz finally accepts, without seeing it, that he will never truly be one of those Black musicians he loves so much, and he hands us his own discovery: <em>to stop being afraid of it</em>. The joy he draws from it is genuine and overwhelming; it comes neither from conquest nor from possession, it comes from his letting go. A harmony found within himself that resembles no one else’s, precisely because it was born of the whole gap between what he wanted to be and what he was. A dissonant harmony, a jazz harmony.</p>"
    },

    "#src-int-2": "<p>That is what this show will be after, and will question: letting go. Through a device that puts it into play — me on stage, and the audience with me, in one and the same experience: what it means to give oneself up, not to hold on, to let go of what one loves.</p>" +
      "<p>This project comes out of my research as an actor-musician: inwardly, I never really tell the two apart; on stage I am both at once, and I question one with the other. What I am after: a music that does not illustrate, a dramaturgy of sound in its own right, acting and music that are not discontinuous — each feeding on the other, made with and against the other. Improvisation is one of its tools: I have always looked for those spaces of freedom in the shows I have passed through, notably alongside Margaux Eskenazi — improvisation as a breach in the textual material, as a natural extension of the writing.</p>" +
      "<p>From intimate narrative to embodiment, from the spoken novel to purely musical moments, from clowning to the music lesson, the piece will be articulated around the multiplicity of layers of reading, of temporalities and of regimes of presence — in the acting as much as in the use of sound on stage.</p>",

    "#src-int-3": "<p>One principle of playing will structure the stage: I will not perform Black artists or thinkers without acknowledging the cost, and I will necessarily do without them in my proposal. It is an ethical rule I impose on myself so as not to repeat certain racist structures already present in the book, and whose constraint I fully accept by making it my own: I will embody by preference the white figures facing them — a Jewish psychoanalyst in session with Charles Mingus (<em>Beneath the Underdog</em>, 1971 — French translation <em>Moins qu’un chien</em>, 1982, co-written with his psychoanalyst); the ORTF interviewer Henri Renaud, a French jazz pianist, facing Thelonious Monk in 1969 (after Alain Gomis’s <em>Rewind and Play</em>, 2022); Boris Vian receiving this music from France (<em>Chroniques de jazz</em>, 1967); Dizzy Gillespie interviewed on the radio (<em>To Be or Not to Bop</em>, 1979).</p>",

    "#src-int-4": "<p>Opening my reading to other jazz autobiographies has been essential: it is what allows me to be in dialogue with Mezz’s own. Some of these voices will come through sounding objects — surface exciters, transducers that make the very material of the object vibrate, a mode of diffusion I want to experiment with alongside conventional loudspeakers. Mingus’s voice coming out of the psychoanalyst’s couch, where the absent body ought to be lying; Dizzy through the radio, the object by which jazz arrived in France…</p>" +
      "<p>Sound will not merely accompany me on stage: it will also be a player in the game with me. Historical recordings, spoken voices, sounding objects — this whole sound world arrives from outside the stage and can, at any moment, take power over me. That escape is not an accident: it is the very nature of this music — what Fred Moten calls fugitivity, that which, in the history of Blackness, resists possession. I cannot possess this music. But it is what makes me play.</p>",

    "#src-int-5": "<p>One dream remains. Mezz wanted to put together a mixed band with Armstrong: it lasted a few weeks. I dream of taking up his gesture — gathering a contemporary band, mixed and gender-balanced, to compose the score of the show to measure, and to collect their spoken voices: what jazz means in their lives today. The living would thus join the dead in the sound world of the show. A creolisation, in Édouard Glissant’s sense: that mixing which produces the unexpected.</p>" +
      "<p>The Kaddish does not mention death. It praises the greatness of the world. It creates a communal (and musical) duration around the absent one without claiming to represent or replace them. It organises a temporal cohabitation with absence.</p>" +
      "<p><em>La Rage de Vivre</em> is a Kaddish that does not know itself: Mezz sanctifies Black musicians with a liturgical fervour, circles what he cannot reach, builds with his words a duration around a Blackness he cannot inhabit. The praise constructs the absence it meant to fill.</p>" +
      "<p>Allen Ginsberg had sensed it: in 1961 he opens his own <em>Kaddish</em> — for his mother Naomi — reciting the Jewish prayer while listening to Ray Charles (<em>Kaddish and Other Poems 1958–1960</em>). The bridge between Kaddish and blues is already drawn. Two parallel forms of speech addressed to an absence — both refusing to name directly what is missing, both creating a duration around the void. A frame held firm — fixed prayer, fixed duration — so that the absent one remains ungrasped. That is the deep form the show is after.</p>",

    "#src-int-6": "<p>I am carrying this project with Margaux Eskenazi. Our shared language has been built over ten years and four productions, since <em>Nous sommes de ceux qui disent non à l’ombre</em> — which dealt with Negritude and its poets (Aimé Césaire, Léon-Gontran Damas, Édouard Glissant) and in which I was already a musician-actor on stage. This solo extends it: a single body on stage, but a rhizome of a show, in Glissant’s sense — no single root, but multiple roots that make relation: the dead, the living, the objects, the control booth, the audience. Alone on stage, and never the centre.</p>",

    /* ══════ Pages 15-17 — texte révélé au scroll ══════
       (pas de clé « .titre-intention » : elle est incluse dans .page-corps--p15
       ci-dessous. Deux sélecteurs qui se recouvrent = retour au FR incomplet.) */
    ".page-corps--p15": "<p class='titre-intention'>Statement of intent</p>" +
      "<p>Ten years ago, <em>La Rage de Vivre</em> imposed itself on me. The autobiography of a Jewish clarinettist and saxophonist from Chicago who spent twenty years trying to become Black by sheer will. A man who never lets go. At the book’s climax, during a musical parade in the prison on Hart’s Island, he lets something go: he improvises, and believes he is finally playing the blues. He believes he grasps its message: life is good, it is good to be alive, in spite of his shortcomings, the difficulty of being in the world, the harshness of life.</p>" +
      "<p>For me that message is not so much the blues’ as, quite simply, his own, Milton Mezzrow’s. In improvising, Mezz finally accepts, without seeing it, that he will never truly be one of those Black musicians he loves so much, and he hands us his own discovery: <em>to stop being afraid of it</em>. The joy he draws from it is genuine and overwhelming; it comes neither from conquest nor from possession, it comes from his letting go. A harmony found within himself that resembles no one else’s, precisely because it was born of the whole gap between what he wanted to be and what he was. A dissonant harmony, a jazz harmony.</p>" +
      "<p>That is what this show will be after, and will question: letting go. Through a device that puts it into play — me on stage, and the audience with me, in one and the same experience: what it means to give oneself up, not to hold on, to let go of what one loves.</p>" +
      "<p>This project comes out of my research as an actor-musician: inwardly, I never really tell the two apart; on stage I am both at once, and I question one with the other. What I am after: a music that does not illustrate, a dramaturgy of sound in its own right, acting and music that are not discontinuous — each feeding on the other, made with and against the other. Improvisation is one of its tools: I have always looked for those spaces of freedom in the shows I have passed through, notably alongside Margaux Eskenazi — improvisation as a breach in the textual material, as a natural extension of the writing.</p>" +
      "<p>From intimate narrative to embodiment, from the spoken novel to purely musical moments, from clowning to the music lesson, the piece will be articulated around the multiplicity of layers of reading, of temporalities and of regimes of presence — in the acting as much as in the use of sound on stage.</p>",

    ".page-corps--p16": "<p>One principle of playing will structure the stage: I will not perform Black artists or thinkers without acknowledging the cost, and I will necessarily do without them in my proposal. It is an ethical rule I impose on myself so as not to repeat certain racist structures already present in the book, and whose constraint I fully accept by making it my own: I will embody by preference the white figures facing them — a Jewish psychoanalyst in session with Charles Mingus (Charles Mingus, <em>Beneath the Underdog</em>, Knopf, 1971 — French translation <em>Moins qu’un chien</em>, Parenthèses, 1982, co-written with his psychoanalyst); the ORTF interviewer Henri Renaud, a French jazz pianist, facing Thelonious Monk in 1969 (after Alain Gomis’s <em>Rewind and Play</em>, 2022); Boris Vian receiving this music from France (<em>Chroniques de jazz</em>, La Jeune Parque, 1967); Dizzy Gillespie interviewed on the radio (Dizzy Gillespie and Al Fraser, <em>To Be or Not to Bop</em>, Doubleday, 1979). Opening my reading to other jazz autobiographies has been essential: it is what allows me to be in dialogue with Mezz’s own.</p>" +
      "<p>Some of these voices will come through sounding objects — surface exciters, transducers that make the very material of the object vibrate, a mode of diffusion I want to experiment with alongside conventional loudspeakers. Mingus’s voice coming out of the psychoanalyst’s couch, where the absent body ought to be lying; Dizzy through the radio, the object by which jazz arrived in France…</p>" +
      "<p>Sound will not merely accompany me on stage: it will also be a player in the game with me. Historical recordings, spoken voices, sounding objects — this whole sound world arrives from outside the stage and can, at any moment, take power over me. That escape is not an accident: it is the very nature of this music — what Fred Moten calls fugitivity, that which, in the history of Blackness, resists possession. I cannot possess this music. But it is what makes me play.</p>",

    ".page-corps--p17": "<p>One dream remains. Mezz wanted to put together a mixed band with Armstrong: it lasted a few weeks. I dream of taking up his gesture — gathering a contemporary band, mixed and gender-balanced, to compose the score of the show to measure, and to collect their spoken voices: what jazz means in their lives today. The living would thus join the dead in the sound world of the show. A creolisation, in Édouard Glissant’s sense: that mixing which produces the unexpected. The Kaddish does not mention death. It praises the greatness of the world. It creates a communal (and musical) duration around the absent one without claiming to represent or replace them. It organises a temporal cohabitation with absence.</p>" +
      "<p><em>La Rage de Vivre</em> is a Kaddish that does not know itself: Mezz sanctifies Black musicians with a liturgical fervour, circles what he cannot reach, builds with his words a duration around a Blackness he cannot inhabit. The praise constructs the absence it meant to fill.</p>" +
      "<p>Allen Ginsberg had sensed it: in 1961 he opens his own <em>Kaddish</em> — for his mother Naomi — reciting the Jewish prayer while listening to Ray Charles (<em>Kaddish and Other Poems 1958–1960</em>). The bridge between Kaddish and blues is already drawn. Two parallel forms of speech addressed to an absence — both refusing to name directly what is missing, both creating a duration around the void. A frame held firm — fixed prayer, fixed duration — so that the absent one remains ungrasped. That is the deep form the show is after.</p>" +
      "<p>I am carrying this project with Margaux Eskenazi. Our shared language has been built over ten years and four productions, since <em>Nous sommes de ceux qui disent non à l’ombre</em> — which dealt with Negritude and its poets (Aimé Césaire, Léon-Gontran Damas, Édouard Glissant) and in which I was already a musician-actor on stage. This solo extends it: a single body on stage, but a rhizome of a show, in Glissant’s sense — no single root, but multiple roots that make relation: the dead, the living, the objects, the control booth, the audience. Alone on stage, and never the centre.</p>" +
      "<p class='signature'>Raphaël Naasz</p>",

    ".cite-marge": "“But to the single root that kills all around it, shall we not dare to set, by way of enlargement, the root as rhizome — the root that opens Relation?”<span class='cite-sig'>Édouard Glissant, <em>Poétique de la Relation</em>, 1990 · trans. from the French</span>",

    /* ══════ Légendes ══════ */
    ".vignette-lat.gauche figcaption": ["Antoine Watteau — Pierrot, c. 1718", "Gregory Crewdson — Boy with Hand in Drain, 1998-2002"],

    /* ══════ Bios ══════ */
    "#src-raph": "<figure><img src='assets/images/raph-naasz.jpg' alt='Raphaël Naasz' data-cap='Raphaël Naasz'><figcaption>Raphaël Naasz</figcaption></figure>" +
      "<p>Raphaël Naasz trained first in music — bassoon and cello — at the Nice conservatoire. That musical training remains at the heart of his work as an actor and director, and the relationship between theatre and music runs through his whole career. In 2013 he entered the Conservatoire National Supérieur d’Art Dramatique (CNSAD), where he worked with Sandy Ouvrier, Nada Strancar, Mario Gonzales, Stuart Seide and Xavier Gallais.</p>" +
      "<p>In 2016 he co-directed, with Antoine Sarrasin, “Blue Train”, a music-theatre piece after Blaise Cendrars’s <em>Prose of the Trans-Siberian</em>, created at the Théâtre de l’Étoile du Nord at the invitation of Sarah Tick. That same year he appeared in auteur cinema in Philippe Garrel’s <em>Lover for a Day</em>.</p>" +
      "<p>In the theatre he has played in “Lourdes” by Paul Toucang (Théâtre National de la Colline, 2017) and in Euripides’s <em>The Bacchae</em>, directed by Marcus Borja, whose work is built on chorus and voice (2017). In 2019 he joined Margaux Eskenazi for “Et le Cœur Fume Encore”. He was Hippolytus in <em>Phèdre</em> (2020), then Treplev in <em>The Seagull</em> (2022), two productions by Brigitte Jacques-Wajeman at the Théâtre de la Ville. He rejoined Margaux Eskenazi for “1983” (2023), then for “Kaddish, la femme chauve en peignoir rouge”, created at the Théâtre Gérard Philipe in Saint-Denis in April 2026.</p>" +
      "<p>In 2022 he made a first short film, “Hémisphère”, and trained in video editing. He is now developing “La Rage de Vivre”, a solo music-theatre piece around jazz, extending the work begun with “Blue Train”.</p>" +
      "<p>Raphaël Naasz performs in <em>Kaddish, la femme chauve en peignoir rouge</em> (Cie Nova, created 2026). <em>La Rage de Vivre</em> hopes to extend, as a solo, certain questions from that cycle — memory, Jewishness, legitimacy — displaced towards jazz.</p>",

    "#src-margaux": "<figure><img src='assets/images/margaux-eskenazi.jpg' alt='Margaux Eskenazi' data-cap='Margaux Eskenazi'><figcaption>Margaux Eskenazi</figcaption></figure>" +
      "<p>A graduate of a research Master’s in Theatre Studies at Paris III and of the directing department of the CNSAD in 2014, Margaux Eskenazi founded Compagnie Nova in 2007. With the company, her work is strongly rooted in Seine-Saint-Denis, where since 2007 she has developed many projects on the territory in connection with her productions. She also teaches in the higher drama schools, leading workshops with students: the École de la Comédie de Saint-Étienne, the ESAD in Paris, the École du Nord in Lille. After working on repertoire texts, she has since 2016 pursued a new line of research she never stops experimenting with: a theatre bringing together the intimate, the political and the poetic. Each show is an exploration of several materials, bringing forth a polysemic and rhizomatic theatricality. All her research centres on the work of memory and on the missing narratives that help us think our identities.</p>" +
      "<p>Between 2016 and 2023 she developed a triptych, “Writing in a Dominated Land”, devoted to colonial amnesia and to the poetics of decolonisation: <em>Nous sommes de ceux qui disent non à l’ombre, Et le cœur fume encore, 1983.</em> In the spring of 2021 Margaux Eskenazi created <em>Gilles ou qu’est-ce qu’un samouraï</em>, after Gilles Deleuze’s lecture <em>What Is the Creative Act?</em></p>" +
      "<p>In January 2024 she created <em>Si Vénus avait su</em>, a piece for non-theatre venues, commissioned by the Théâtre de la Poudrerie (Sevran) and devoted to socio-aestheticians. She also created the graduating show of the Belle Troupe in June 2024 at the Théâtre de Nanterre-Amandiers, <em>Kaddish-mémoires</em>, around the literature of Imre Kertész. In the summer of 2025 she created a piece devoted to the girls of the Bon Pasteur for the 17<sup>th</sup> edition of the Nouveau Théâtre Populaire festival.</p>" +
      "<p>For the 2025-2026 season, Margaux Eskenazi created <em>Kaddish, la femme chauve en peignoir rouge</em>, around Jewish identities in France today. She is preparing a young-audience show for autumn 2026 and is adapting, with Julie Deliquet and Julie André, Peter Weiss’s <em>The Investigation</em>, scheduled for autumn 2027 at the Théâtre National de la Colline.</p>",

    "#src-julia": "<figure><picture><source srcset='assets/images/julia-baudet.webp' type='image/webp'><img src='assets/images/julia-baudet.jpg' alt='Julia Baudet' data-cap='Julia Baudet'></picture><figcaption>Julia Baudet</figcaption></figure>" +
      "<p>Originally from Annecy, Julia Baudet moved to Paris at eighteen to train in theatre. She studied successively at La Générale, at the Studio Théâtral d’Ivry and then at the Conservatoire of the 14<sup>th</sup> arrondissement, before continuing her training in London at the Fourth Monkey Actor Training Company, from which she graduated in 2021.</p>" +
      "<p>Since returning to France she has worked with several theatre companies, notably La Tronçonneuse, led by Ambre Maton, J’ai tué mon bouc, led by Louis Berthelémy, the collective Les Assoiffés d’Azur, and the Compagnie des Méridiens. With the latter she took part in a schools tour around a contemporary text on youth, presented in several venues in eastern France.</p>" +
      "<p>Between 2024 and 2026 she worked with Les Assoiffés d’Azur on several forms inspired by <em>Romeo and Juliet</em>, continuing her exploration of Shakespeare’s work. In 2026, with the company J’ai tué mon bouc, she took part in the creation of an Elizabethan cabaret mixing theatre and song, presented at the Théâtre de la Barcarolle and then at the Théâtre d’Hardelot.</p>" +
      "<p>She also works as an assistant director, with Louis Berthelémy on <em>PLOUK(S)</em> in 2019 and then with Christophe Montenez of the Comédie-Française on <em>Mondes possibles</em> in 2026.</p>" +
      "<p>Alongside her acting she pursues, self-taught, a body of drawing and painting. Her work has been exhibited in Annecy, Paris and London. She is also involved in organising the Festival de Malaz in Annecy.</p>",

    /* ══════ Contacts (on ne touche pas aux liens mailto) ══════ */
    ".contact-liste .c-role": ["writer, performer, musician", "director", "assistant director"]
  }
};
